# vim: set ft=ansible:
---
- hosts: localhost
  connection: local
  sudo: no
  gather_facts: no
  vars_files:
  - ../vars.yml
  vars:
    cluster_hosts: "{{ groups['tag_env_' ~ cluster_id] }}"
  tasks:
  - fail:
      msg: required values not set
    when: rhsm_user is not defined or rhsm_pass is not defined or cluster_id is not defined

  - add_host:
      name: "{{ item }}"
      ansible_ssh_user: openshift
      ansible_sudo: yes
      groups: oo_hosts_to_register
    with_items: cluster_hosts

- name: Repository configuration
  hosts: oo_hosts_to_register
  tasks:

  - name: Configure OSE repository
    copy: 
      src: ../files/ose3.repo
      dest: /etc/yum.repos.d/ose3.repo
      mode: 0644
      owner: root
      group: root

  - name: Enable rhui extras channel
    command: yum-config-manager --enable rhui-REGION-rhel-server-extras

  - name: Update current package set
    yum:
      name: '*'
      state: latest

